name: flutter_slideshow
description: Image slideshow with functionalities like share, favorite and change wallpaper.
maintainer: Naz (@nramirez)
homepage: https://github.com/nramirez/slideshow
repository: https://github.com/nramirez/slideshow
issue_tracker: https://github.com/nramirez/slideshow/issues
version: 1.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  bg: ^1.0.2
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  share_plus: ^6.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
